Fix more tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -64,11 +64,15 @@ jobs:
           name: ${{ github.run_id }}-tests-${{ matrix.test_file }}
           path: ${{ matrix.test_file }}.xml
 
-      - name: Print XML content
-        run: cat ${{ matrix.test_file }}.xml
-      
-      - name: Fail on failure or error
-        run: grep -Eq "<failure|error" ${{ matrix.test_file }}.xml; if [ $? -eq 0 ]; then exit 1; else exit 0; fi
+      - name: Check for failures or errors
+        run: |
+          if grep -Eq "<failure|error" test_primitives.xml; then
+            echo "Found failure or error in test_primitives.xml"
+            exit 1
+          else
+            echo "No failures or errors found in test_primitives.xml"
+            exit 0
+          fi
 
   upload_report:
     name: Compile Report
